version: '3.7'

services:
  mongo:
      image: mongo:latest
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${TYPEORM_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${TYPEORM_PASSWORD}
      ports:
        - 27017:27017
  mongo-express:
      image: mongo-express
      environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        - ME_CONFIG_MONGODB_AUTH_USERNAME=${TYPEORM_USERNAME}
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=${TYPEORM_PASSWORD}
        - ME_CONFIG_BASICAUTH_USERNAME=dev
        - ME_CONFIG_BASICAUTH_PASSWORD=dev
      ports:
        - "8888:8081"